name: comfyui
services:
    comfyui:
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities:
                              - gpu
        volumes:
            - ./data:/storage
        ports:
            - 8188:8188
        container_name: comfyui
        build: .
        restart: always